<a href="https://colab.research.google.com/github/CoderCouple/numpy_tutorial_practice1/blob/main/01_np_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basic of numpy arrays

In [ ]:
import numpy as np

In [ ]:
# 1-D Array
ints = [-2,-1, 0, 1, 2]
np_array = np.array(ints)
print(np_array)
print(np_array.dtype)

[-2 -1  0  1  2]
int64


In [ ]:
# 2-D Array
matrix = np.array([
    [1,2,3,4],
    [5,6,7,8]
])

print(matrix)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
# 3-D Array
tensor = np.array([
    [[1,2,3],
     [4,5,6]],
    [[7,8,9],
     [9,8,7]]
])
print(tensor)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [9 8 7]]]


In [ ]:
ints = [-2,-1, 0, 1, 2]
np_array = np.array(ints, dtype=np.short)
print(np_array)
print(np_array.dtype)

[-2 -1  0  1  2]
int16


In [ ]:
unsigned_ints= np.array([-2,-1, 0, 1, 2], dtype=np.ushort)
print(unsigned_ints)

OverflowError: Python integer -2 out of bounds for uint16