<a href="https://colab.research.google.com/github/CoderCouple/numpy_tutorial_practice1/blob/main/02_np_1D_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy 1-D basic array creation

In [ ]:
import numpy as np

In [ ]:
# 1-D array
array1 = np.arange(3)
print(array1)

[0 1 2]


In [ ]:
# 1-D array
array2 = np.arange(-2, 5)
print(array2)

[-2 -1  0  1  2  3  4]


In [ ]:
array3 = np.arange(0,11,2)
print(array3)

[ 0  2  4  6  8 10]


In [ ]:
array4 = np.arange(-1,-4,-1)
print(array4)

[-1 -2 -3]


In [ ]:
array5 = np.arange(0.1,0.3,0.1)
print(array5)

[0.1 0.2]


In [ ]:
array6 = np.linspace(0.1,0.3,3)
print(array6)

[0.1 0.2 0.3]
