<a href="https://colab.research.google.com/github/CoderCouple/numpy_tutorial_practice1/blob/main/03_np_2D_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy 2D Arrays

In [ ]:
import numpy as np

In [ ]:
identity_3X3 = np.eye(3)
print(identity_3X3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
indentity_3X4 = np.eye(3,4)
print(indentity_3X4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [ ]:
dialgonal_2d= np.diag([1,2,3,4,5])
print(dialgonal_2d)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [ ]:
diag_array = np.array([
 [1, 0, 0, 0, 0],
 [0, 2, 0, 0, 0],
 [0, 0, 3, 0, 0],
 [0, 0, 0, 4, 0],
 [0, 0, 0, 0, 5]
])
diag_elements = np.diag(diag_array)
print(diag_elements)

[1 2 3 4 5]
