<a href="https://colab.research.google.com/github/CoderCouple/numpy_tutorial_practice1/blob/main/numpy_array_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
A = np.arange(12).reshape(3,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
A.shape

(3, 4)

In [ ]:
A.dtype

dtype('int64')

In [ ]:
A.strides

(32, 8)

In [ ]:
FA = np.asfortranarray(A)
FA

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
FA.shape

(3, 4)

In [ ]:
FA.strides

(8, 24)

In [ ]:
B = A[:,1:3]
B

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [ ]:
B.base is A

False

In [ ]:
np.may_share_memory(A,B)

True

In [ ]:
B[0,0] = 55

In [ ]:
A

array([[ 0, 55,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
C = A[:, [1,3]]
C

array([[55,  3],
       [ 5,  7],
       [ 9, 11]])

In [ ]:
C.base is A

False

In [ ]:
np.may_share_memory(A,C)

False

In [ ]:
D = A.astype(np.float32)

In [ ]:
E = A.view()
E

array([[ 0, 55,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])